// snes_examples — writes the example cartridges to disk.
//
//   snes_examples <directory>
//
// Writes every cartridge in `examples/example_cartridges.h` under the directory
// as `<name>.smc`, creating the directory, and lists each with what it does.
// These are the cartridges the tests read and the documentation's examples are
// produced from, so a page's output can be regenerated by running the tool it
// shows on the cartridge it names.
//
// The exit status is 0 when every file was written, 2 on a bad argument, 1 when
// a file could not be written.

#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>
#include <system_error>

#include "examples/example_cartridges.h"

int main(int argc, char** argv) {
  if (argc != 2) {
    std::cerr << "usage: " << argv[0] << " <directory>\n"
                 "  writes every example cartridge under the directory as <name>.smc\n";
    return 2;
  }
  const std::filesystem::path directory = argv[1];
  std::error_code ec;
  std::filesystem::create_directories(directory, ec);
  for (const snaggletooth::examples::Example& example : snaggletooth::examples::examples()) {
    const std::vector<std::uint8_t> image = example.build();
    const std::filesystem::path path = directory / (std::string(example.name) + ".smc");
    std::ofstream out(path, std::ios::binary);
    if (!out) {
      std::cerr << "cannot write " << path.string() << "\n";
      return 1;
    }
    out.write(reinterpret_cast<const char*>(image.data()), static_cast<std::streamsize>(image.size()));
    if (!out) {
      std::cerr << "cannot write " << path.string() << "\n";
      return 1;
    }
    std::cout << path.filename().string() << "  " << image.size() << " bytes  " << example.description
              << "\n";
  }
  return 0;
}
