#!/usr/bin/env python3
"""Transcribes the S-DSP's documented constant tables into generated C++ includes.

The S-DSP's Gaussian interpolation table is hardware ROM data: the documented
values deviate from the theoretical Gaussian curve (four-tap sums land in
7FFh..801h rather than a constant 800h), so the table cannot be regenerated
from a formula — it must be transcribed from the hardware references. This
tool reads two independent public references, cross-checks them entry by
entry, and emits the table as a C++ initializer fragment. Any disagreement
between the references is a hard failure: the tool refuses to emit.

References (pass local copies as arguments; they are not part of this repo):
  - fullsnes ("SNES APU DSP BRR Pitch" section), problemkaputt.de/fullsnes.htm,
    converted to plain text. The emitted values come from this document.
  - Anomie's S-DSP document (the printed gauss[512] array), used solely as the
    cross-check copy.

Usage:
  python3 tools/parse_dsp_tables.py gauss \
      --fullsnes <path to fullsnes text> \
      --anomie <path to anomie s-dsp text> \
      --out src/generated/gauss_table.inc

Python 3 standard library only.
"""

import argparse
import re
import sys

GAUSS_SIZE = 512

FULLSNES_GAUSS_ANCHOR = "The Gauss table contains the following values (in hex):"
ANOMIE_GAUSS_ANCHOR_RE = re.compile(r"gauss\s*\[\s*512\s*\]\s*=\s*\{")


def fail(message):
    sys.exit(f"parse_dsp_tables: {message}")


def read_lines(path):
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            return f.read().splitlines()
    except OSError as e:
        fail(f"cannot read {path}: {e}")


def parse_fullsnes_gauss(path):
    """Parses the 32-row hex block that follows the fullsnes anchor line.

    Rows look like:  104,107,10B,...,137  ;
    Everything from the first ';' on a row is commentary and is dropped.
    """
    lines = read_lines(path)
    try:
        start = next(i for i, line in enumerate(lines) if FULLSNES_GAUSS_ANCHOR in line)
    except StopIteration:
        fail(f"fullsnes anchor line not found in {path!r}: {FULLSNES_GAUSS_ANCHOR!r}")

    values = []
    for line in lines[start + 1 :]:
        row = line.split(";", 1)[0]
        tokens = [t for t in re.split(r"[\s,]+", row) if t]
        if not tokens:
            if values:
                break  # a blank row after data ends the block
            continue  # blank rows between the anchor and the data
        for token in tokens:
            if not re.fullmatch(r"[0-9A-Fa-f]{3}", token):
                fail(f"fullsnes table row holds a non-hex token {token!r}: {line!r}")
            values.append(int(token, 16))
        if len(values) >= GAUSS_SIZE:
            break

    if len(values) != GAUSS_SIZE:
        fail(f"fullsnes table parsed {len(values)} values, expected {GAUSS_SIZE}")
    return values


def parse_anomie_gauss(path):
    """Parses the 0x-prefixed gauss[512] array printed in Anomie's document."""
    lines = read_lines(path)
    try:
        start = next(i for i, line in enumerate(lines) if ANOMIE_GAUSS_ANCHOR_RE.search(line))
    except StopIteration:
        fail(f"anomie anchor 'gauss[512] = {{' not found in {path!r}")

    values = []
    for line in lines[start + 1 :]:
        if "}" in line:
            line = line.split("}", 1)[0]
            tokens = re.findall(r"0x([0-9A-Fa-f]{1,4})", line)
            values.extend(int(t, 16) for t in tokens)
            break
        tokens = re.findall(r"0x([0-9A-Fa-f]{1,4})", line)
        values.extend(int(t, 16) for t in tokens)
        if len(values) > GAUSS_SIZE:
            break

    if len(values) != GAUSS_SIZE:
        fail(f"anomie table parsed {len(values)} values, expected {GAUSS_SIZE}")
    return values


def cross_check(primary, check, primary_name, check_name):
    mismatches = [
        (i, a, b) for i, (a, b) in enumerate(zip(primary, check)) if a != b
    ]
    if mismatches:
        detail = ", ".join(
            f"[{i:#05x}] {primary_name}={a:#05x} {check_name}={b:#05x}"
            for i, a, b in mismatches[:8]
        )
        count = len(mismatches)
        noun = "entry disagrees" if count == 1 else "entries disagree"
        fail(f"{count} {noun} between {primary_name} and {check_name}: {detail}")


def emit_gauss(values, out_path):
    header = (
        "// AUTO-GENERATED by tools/parse_dsp_tables.py — DO NOT EDIT BY HAND.\n"
        "//\n"
        "// The S-DSP's 512-entry Gaussian interpolation table, transcribed from\n"
        "// fullsnes (problemkaputt.de/fullsnes.htm, \"SNES APU DSP BRR Pitch\") and\n"
        "// cross-checked entry by entry against the copy printed in Anomie's S-DSP\n"
        "// document. This is hardware ROM data: the values deviate from the\n"
        "// theoretical Gaussian curve (four-tap sums land in 7FFh..801h, not a\n"
        "// constant 800h), so the table is transcribed, never regenerated from a\n"
        "// formula.\n"
        "//\n"
        "// Regenerate with:\n"
        "//   python3 tools/parse_dsp_tables.py gauss \\\n"
        "//       --fullsnes <fullsnes text> --anomie <anomie s-dsp text> \\\n"
        "//       --out src/generated/gauss_table.inc\n"
    )
    rows = []
    for i in range(0, GAUSS_SIZE, 16):
        row = ", ".join(f"0x{v:03X}" for v in values[i : i + 16])
        rows.append(f"{row},\n")
    try:
        with open(out_path, "w", encoding="utf-8", newline="\n") as f:
            f.write(header)
            f.writelines(rows)
    except OSError as e:
        fail(f"cannot write {out_path}: {e}")


def cmd_gauss(args):
    fullsnes = parse_fullsnes_gauss(args.fullsnes)
    anomie = parse_anomie_gauss(args.anomie)
    cross_check(fullsnes, anomie, "fullsnes", "anomie")
    emit_gauss(fullsnes, args.out)
    print(f"gauss: {GAUSS_SIZE} entries cross-checked, written to {args.out}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    gauss = sub.add_parser("gauss", help="transcribe the Gaussian interpolation table")
    gauss.add_argument("--fullsnes", required=True, help="path to the fullsnes plain text")
    gauss.add_argument("--anomie", required=True, help="path to Anomie's S-DSP document")
    gauss.add_argument("--out", required=True, help="output .inc path")
    gauss.set_defaults(func=cmd_gauss)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
